name: Build Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        dotnet-version: [6.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install client dependencies
      working-directory: ./healthcheck.client
      run: npm install

    - name: Build Angular client
      working-directory: client
      run: ng build --prod

    - name: Restore .NET dependencies
      working-directory: server
      run: dotnet restore

    - name: Build .NET project
      working-directory: server
      run: dotnet build --configuration Release --no-restore
